# Generated by Django 4.0.1 on 2022-01-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vet',
            old_name='isactive',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='fees',
        ),
        migrations.AddField(
            model_name='vet',
            name='fees',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='cancel',
            field=models.BooleanField(null=True),
        ),
    ]
