# Generated by Django 4.0.1 on 2022-01-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_isactive_vet_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='cancel_reason',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
