# Generated by Django 4.0.1 on 2022-03-09 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_rename_complete_order_payment_complete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_complete',
            new_name='complete',
        ),
    ]
